### ISSUE TITLE
Comments Section [discussion]

### ISSUE THREAD

**Issue by Rushi98** [Devsoc-BPGC/ARD#131]
We require comments at many places. One example is #80 . There would be other places such as discussion on announcements, uploads and posts or even standalone topics which contain only discussion. Instead of developing comment sections individually for each of these, we should develop a single module (in form of a fragment, maybe?) and reuse it.

**Comment by kukreja-vikramaditya** [comment]
Yes I agree. Using fragment will also be a good idea.
I can think of 2 cases here, maybe we can divide them and approach the issues .
1. Quick comment section in the HomeFragment list
2. Detailed comment section in a "Detailed Activity" 

However this requires authentication and is blocked until #125  is merged

**Comment by Rushi98** [comment]
Now that #43 is complete, should we complete this. Also, this will be a part of #143 .

**Comment by kukreja-vikramaditya** [comment]
I am currently creating the backbone in #143.
Once that is completed this can be resolved

**Comment by Rushi98** [comment]
closing as stale
