### ISSUE TITLE
Put all posts in same node irrespective of type.

### ISSUE THREAD

**Issue by Rushi98** [Devsoc-BPGC/ARD#151]
A post child will have only relevant data and an attribute specifying its type.
This will help us in simplifying code. (Ex- to sort by date, author). And also will avoid repetition of code (ex- We can have a generic discussion activity with only non null data shown.)

**Comment by kukreja-vikramaditya** [comment]
Are you suggesting that posts should inherit from a more general model ->
PostItem (something like that) and keep extending and adding as per requirement?

**Comment by Rushi98** [comment]
Yes

**Comment by Rushi98** [comment]
closing as stale
